openapi: 3.1.0
info:
  title: Personal Recipe Book API
  version: 0.1.0
  description: >-
    REST & WebSocket endpoints for creating, editing, and managing personal
    recipes. All endpoints are **user-scoped** - authenticated users can only
    access and modify their own recipes. Authentication required via JWT Bearer token.
servers:
  - url: https://api.myrecipes.app
security:
  - bearerAuth: []
paths:
  /v1/auth/signup:
    post:
      summary: Create new user account with email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, confirmPassword]
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address (must be unique)
                password:
                  type: string
                  minLength: 8
                  description: Password with at least one letter and one number
                confirmPassword:
                  type: string
                  description: Must match password field
      responses:
        "201":
          description: Account created successfully.
          content:
            application/json:
              schema:
                type: object
                required: [access_token, refresh_token, user]
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        "400": { $ref: '#/components/responses/BadRequest' }
        "409":
          description: Email already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/auth/signin:
    post:
      summary: Authenticate existing user with email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        "200":
          description: Authentication successful.
          content:
            application/json:
              schema:
                type: object
                required: [access_token, refresh_token, user]
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        "400": { $ref: '#/components/responses/BadRequest' }
        "401":
          description: Invalid credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/auth/forgot-password:
    post:
      summary: Send password reset email.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
                  format: email
      responses:
        "200":
          description: Reset instructions sent if account exists.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "If an account exists with this email, you'll receive password reset instructions"
        "400": { $ref: '#/components/responses/BadRequest' }

  /v1/auth/reset-password:
    post:
      summary: Reset password with token from email.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [token, newPassword]
              properties:
                token:
                  type: string
                  description: Reset token from email
                newPassword:
                  type: string
                  minLength: 8
                  description: New password with at least one letter and one number
      responses:
        "200":
          description: Password reset successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Password updated successfully"
        "400": { $ref: '#/components/responses/BadRequest' }
        "401":
          description: Invalid or expired reset token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/auth/refresh:
    post:
      summary: Refresh access token using refresh token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [refresh_token]
              properties:
                refresh_token:
                  type: string
      responses:
        "200":
          description: Token refreshed successfully.
          content:
            application/json:
              schema:
                type: object
                required: [access_token, refresh_token]
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
        "401": { $ref: '#/components/responses/Unauthorized' }

  /v1/auth/logout:
    post:
      summary: Invalidate refresh token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [refresh_token]
              properties:
                refresh_token:
                  type: string
      responses:
        "200":
          description: Logout successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Logged out successfully"
        "400": { $ref: '#/components/responses/BadRequest' }

  /v1/recipes:
    post:
      summary: Create a recipe for the authenticated user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
      responses:
        "201":
          description: Recipe created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        "422": { $ref: '#/components/responses/ValidationError' }
    get:
      summary: List all recipes for the authenticated user.
      responses:
        "200":
          description: Array of user's recipes in reverse chronological order.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeSummary'

  /v1/recipes/{recipeId}:
    parameters:
      - $ref: '#/components/parameters/recipeId'
    get:
      summary: Fetch a recipe owned by the authenticated user.
      responses:
        "200":
          description: Recipe object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        "404": { $ref: '#/components/responses/NotFound' }
    patch:
      summary: Update a recipe owned by the authenticated user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipePatch'
      responses:
        "200":
          description: Updated recipe.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        "422": { $ref: '#/components/responses/ValidationError' }
    delete:
      summary: Delete a recipe owned by the authenticated user.
      responses:
        "204":
          description: Recipe deleted successfully.
        "404": { $ref: '#/components/responses/NotFound' }


  # WebSocket definition (non‑standard OpenAPI) for chat
  x-websocket:
    /v1/chat/{recipeId}:
      description: Bidirectional chat stream for recipe editing.
      bindings:
        recipeId:
          $ref: '#/components/parameters/recipeId'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    recipeId:
      name: recipeId
      in: path
      required: true
      schema:
        type: string
        format: uuid

  responses:
    BadRequest:
      description: Invalid request payload.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ValidationError:
      description: Payload failed schema validation.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Authentication required or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Recipe:
      $ref: 'recipe-schema.json'
    RecipeSummary:
      type: object
      required: [id, title, yield, updated_at]
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        yield:
          type: string
        updated_at:
          type: string
          format: date-time
    RecipePatch:
      description: >-
        Partial update payload; any Recipe field can be provided. The backend
        performs validation and merges with latest version, returning new
        version of the Recipe.
      type: object
      allOf:
        - $ref: '#/components/schemas/Recipe'
      example:
        title: "Classic Pancakes (Gluten‑Free)"
    User:
      type: object
      required: [id, email, name, created_at]
      properties:
        id:
          type: string
          format: uuid
          description: Unique user identifier
        email:
          type: string
          format: email
          description: User's email address
        name:
          type: string
          description: User's display name
        created_at:
          type: string
          format: date-time
          description: Account creation timestamp
    Error:
      type: object
      required: [error, message]
      properties:
        error:
          type: string
          description: Machine-readable error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error context